export const EN_US_COPY = {
  settings: 'Settings',
  closeSettings: 'Close settings',
  tutorial: 'Tutorial',
  openTutorial: 'Open tutorial',
  closeTutorial: 'Close tutorial',
  tutorialTitle: 'Quick start',
  tutorialIntro: 'Follow these steps to hand an Android control task to the agent.',
  tutorialSteps: [
    {
      title: 'Connect Android device',
      body: 'Enable USB debugging, plug in the phone, then click Connect in the device panel and authorize ADB on the phone.',
    },
    {
      title: 'Configure model',
      body: 'Fill in Base URL, API Key, and Model in model settings; choose pixel JSON or normalized 0-1000 JSON coordinates if needed.',
    },
    {
      title: 'Send a task',
      body: 'Type a concrete goal in chat, such as opening Settings and entering Wi-Fi; sending captures the screen and asks for the next action.',
    },
    {
      title: 'Watch and take over',
      body: 'Review pending actions, step details, and the run log while it runs; take over manually for sensitive flows or verification codes.',
    },
  ],
  tutorialNotesTitle: 'Good habits',
  tutorialNotes: [
    'Start with a simple task to confirm screenshots, coordinates, and text input all work.',
    'Keep human confirmation enabled for login, payment, deletion, authorization, and other high-risk flows.',
    'Edit App Cards in settings for common apps; Secrets and Custom Tools stay in this local browser.',
  ],
  tutorialFaqTitle: 'FAQ',
  tutorialFaqItems: [
    {
      question: 'What should I do if the device will not connect?',
      answer:
        'If the connection fails, run adb kill-server in your terminal, then reconnect the device. Also confirm WebUSB support, enable USB debugging, and approve the prompt on the phone.',
    },
    {
      question: 'Why does the agent stop before running?',
      answer:
        'Check Base URL, API Key, and Model. You can also run Doctor to inspect model and device connectivity.',
    },
    {
      question: 'What if taps land in the wrong place?',
      answer:
        'Capture a fresh screenshot first and confirm the preview is current. The app maps model screenshot coordinates back to the native device screen before execution.',
    },
    {
      question: 'What if Chinese text or clearing text fails?',
      answer:
        'Use Enable ADB text input to install or enable ADB Keyboard, then enable Use ADB Keyboard for text in the left-side device options.',
    },
    {
      question: 'How are login, payment, and verification-code flows handled?',
      answer:
        'Keep sensitive action confirmation enabled. Take over manually for passwords, verification codes, payments, deletion, and authorization steps.',
    },
  ],
  agentContextRestored: 'Agent context restored',
  agentContextRestoreSkipped: 'Agent context restore skipped',
  connectDeviceTask: 'Connect device',
  captureScreenTask: 'Capture screen',
  deviceConnected: 'Device connected',
  deviceDisconnected: 'Device disconnected',
  disconnectDeviceTask: 'Disconnect device',
  executeActionTask: 'Execute action',
  executedAction: (preview: string) => `Executed ${preview}`,
  failedAction: (preview: string) => `Failed ${preview}`,
  failedToDownloadAdbKeyboard: (status: number) =>
    `Failed to download ADB Keyboard APK: HTTP ${status}.`,
  language: 'Language',
  languageSystem: 'System default',
  languageChinese: '中文',
  languageEnglish: 'English',
  appDescription:
    'Browser-based Android automation console for WebADB and OpenAI-compatible vision models.',
  appTagline: 'Browser + WebADB + vision model = a phone-agent playground',
  appFeatures: [
    'Runs fully in the browser, no backend on static deploys',
    'Connect Android devices via WebUSB/WebADB',
    'Vision models read the screenshot and return controlled actions',
    'JSON action protocols: pixel or normalized coordinates',
    'Auto-execution loop with sensitive-action confirmation',
  ],
  githubRepository: 'GitHub repository',
  repositoryStats: 'Repository stats',
  stars: 'Stars',
  forks: 'Forks',
  openIssues: 'Open issues',
  githubStatsError: 'Could not load GitHub stats right now.',
  theme: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  taskNotifications: 'Task notifications',
  localCache: 'Local cache',
  localCacheUsage: 'Local cache usage',
  localCacheLoading: 'Checking...',
  localCacheUnavailable: 'Unavailable in this browser',
  localCacheError: 'Could not read cache usage',
  localCacheUsageOf: (usage: string, quota: string) => `${usage} of ${quota}`,
  localCacheUsageOnly: (usage: string) => `${usage} used`,
  dataManagement: 'Data management',
  dataManagementShort: 'Data',
  settingsPreferences: 'Preferences',
  settingsPreferencesShort: 'Prefs',
  settingsResources: 'Resources',
  settingsResourcesShort: 'Res',
  settingsProjectInfo: 'Project',
  settingsProjectInfoShort: 'Proj',
  appVersion: 'Version',
  clearChatHistory: 'Clear chat history',
  clearRunLog: 'Clear run log',
  chatHistoryCleared: 'Chat history cleared',
  exportChatHistory: 'Export chat history',
  importChatHistory: 'Import chat history',
  exportSettings: 'Export settings',
  importSettings: 'Import settings',
  chatHistoryExported: (count: number) => `Exported ${count} chat${count === 1 ? '' : 's'}`,
  chatHistoryImported: (count: number) => `Imported ${count} chat${count === 1 ? '' : 's'}`,
  settingsExported: 'Settings exported',
  settingsImported: 'Settings imported',
  importInvalidFile: 'Invalid import file',
  importFailed: (detail: string) => `Import failed: ${detail}`,
  appCards: 'App cards',
  appCardsJson: 'App cards JSON',
  resetAppCards: 'Reset',
  secrets: 'Secrets',
  secretsJson: 'Secrets JSON',
  customTools: 'Custom tools',
  customToolsJson: 'Custom tools JSON',
  actionTools: 'Action tools',
  actionToolsHelp:
    'Turn individual tools on or off. Disabled tools are hidden from the model and blocked if a queued action still tries to run them.',
  actionToolEnabled: 'Enabled',
  actionToolDisabled: 'Disabled',
  actionToolToggle: (name: string) => `Toggle ${name}`,
  actionToolsSummary: (enabled: number, total: number) => `${enabled}/${total} enabled`,
  actionToolSearch: 'Search action tools',
  actionToolSearchPlaceholder: 'Search tools...',
  actionToolSearchClear: 'Clear tool search',
  actionToolFilter: 'Action tool filter',
  actionToolFilterAll: 'All',
  actionToolFilterEnabled: 'Enabled',
  actionToolFilterDisabled: 'Disabled',
  noActionToolSearchResults: (query: string) => `No tools match "${query}"`,
  noActionToolsInFilter: (filter: 'all' | 'disabled' | 'enabled') =>
    filter === 'disabled' ? 'No disabled tools.' : 'No tools in this view.',
  memory: 'Memory',
  memoryHelp:
    'Allow WebDroid to save short local facts from note and reuse them in later tasks.',
  configurationPanel: 'Configuration',
  collapseConfigurationPanel: 'Collapse configuration panel',
  expandConfigurationPanel: 'Expand configuration panel',
  openConfigurationSection: (section: string) => `Open ${section}`,
  readinessStatus: 'Readiness',
  deviceReadyShort: 'connected',
  deviceNotReadyShort: 'offline',
  agentReady: 'Ready',
  agentNotReady: 'Setup needed',
  readinessNeedsDevice: 'Connect a device',
  readinessNeedsModel: 'Configure a model',
  readinessNeedsBoth: 'Next: connect device · configure model',
  agentRunningStatus: 'Running',
  agentRunningStep: (step: number) => `Running · step ${step}`,
  workspaceTabs: 'Workspace',
  workspaceTabPhone: 'Screen',
  workspaceTabChat: 'Chat',
  workspaceTabConfig: 'Config',
  webUsbReady: 'ready',
  webUsbMissing: 'missing',
  setupHomeAria: 'Getting started',
  setupHomeTitle: 'Get started with WebDroid Agent',
  setupHomeIntro:
    'Connect your phone and configure a vision model, then control Android with natural language.',
  setupStepDeviceTitle: 'Connect an Android device',
  setupStepDeviceBody:
    'Enable USB debugging, plug in the phone, and authorize ADB debugging when prompted.',
  setupStepDeviceAction: 'Connect device',
  setupStepDeviceDone: 'Device connected',
  setupStepModelTitle: 'Configure a vision model',
  setupStepModelBody:
    'Provide Base URL, API Key, and Model so the agent can read screenshots and plan actions.',
  setupStepModelAction: 'Configure model',
  setupStepModelDone: 'Model ready',
  setupStepTaskTitle: 'Send a task',
  setupStepTaskBody: 'Describe a goal in chat, for example open Settings and go to Wi-Fi.',
  setupStepTaskAction: 'Open workspace',
  setupStepTaskLocked: 'Finish the first two steps to send tasks',
  setupSkipToWorkspace: 'Skip to workspace',
  setupRequirementBrowser: 'Chrome / Edge or another Chromium browser',
  setupRequirementUsb: 'Android device with USB debugging enabled',
  setupRequirementModel: 'Vision model that accepts screenshot input',
  setupWebUsbMissing: 'This browser does not support WebUSB. Please use Chrome or Edge.',
  model: 'Model',
  noModel: 'No model',
  modelSettings: 'Model settings',
  modelConfigurationStatus: 'Model configuration status',
  modelConfigurationReady: 'Ready to run',
  modelConfigurationReadyShort: 'Ready',
  modelConfigurationRequiredNext: 'Required next',
  modelConfigurationRequiredNextShort: 'Setup',
  modelConfigurationNeedsField: (field: string) => `Needs ${field}`,
  modelConfigurationFieldRequired: (field: string) =>
    `${field} is required before the agent can run.`,
  provider: 'Provider',
  providerCustom: 'OpenAI Compatible',
  providerOpenAi: 'OpenAI',
  providerQwen: 'Qwen',
  providerGemini: 'Gemini',
  geminiNativeModeNotice:
    'Uses the native Gemini generateContent API (key in the query string). Thinking depth follows the Gemini thinkingLevel mapping.',
  openaiOfficialModeNotice:
    'Uses the official OpenAI Responses API for GPT-5.6 series models. Reasoning effort, pro mode, and summary map to the nested reasoning.* parameters.',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  showApiKey: 'Show API key',
  hideApiKey: 'Hide API key',
  reasoningEffort: 'Thinking depth',
  reasoningEffortDefault: 'Provider default',
  reasoningEffortNone: 'None',
  reasoningEffortMinimal: 'Minimal',
  reasoningEffortLow: 'Low',
  reasoningEffortMedium: 'Medium',
  reasoningEffortHigh: 'High',
  reasoningEffortXHigh: 'Extra high',
  reasoningEffortMax: 'Max',
  openaiReasoningMode: 'Reasoning mode',
  openaiReasoningModeStandard: 'Standard',
  openaiReasoningModePro: 'Pro',
  openaiReasoningSummary: 'Reasoning summary',
  openaiReasoningSummaryOff: 'Off',
  openaiReasoningSummaryAuto: 'Auto',
  openaiReasoningSummaryConcise: 'Concise',
  openaiReasoningSummaryDetailed: 'Detailed',
  qwenThinkingMode: 'Thinking mode',
  qwenThinkingBudget: 'Thinking budget',
  actionProtocol: 'Action protocol',
  actionProtocolWebDroidJson: 'WebDroid JSON',
  actionProtocolWebDroidNormalizedJson: 'WebDroid Normalized JSON (0-1000)',
  streamModelResponses: 'Stream model responses',
  device: 'Device',
  noDevice: 'No device',
  deviceDetails: 'Device details',
  serial: 'Serial',
  currentApp: 'Current app',
  unknownApp: 'Unknown',
  package: 'Package',
  activity: 'Activity',
  keyboard: 'Keyboard',
  usbDebuggingRequired: 'USB debugging required',
  connect: 'Connect',
  adbConnectionHelpLabel: 'ADB connection help',
  adbConnectionHelpText:
    'If the connection fails, run adb kill-server in your terminal, then reconnect the device.',
  disconnect: 'Disconnect',
  capture: 'Capture',
  configureTextInput: 'Enable ADB text input',
  adbKeyboardConfigured: 'ADB text input enabled',
  tools: 'Tools',
  toolsSummary: (count: number) => `${count} tools`,
  runDoctor: 'Run Doctor',
  doctorChecks: 'Doctor checks',
  doctorChecksOk: 'Checks OK',
  doctorIssues: 'Check issues',
  doctorSummary: 'Doctor summary',
  installedApps: 'Installed apps',
  closeInstalledApps: 'Close installed apps',
  appSearch: 'App search',
  clearAppSearch: 'Clear app search',
  launchApp: 'Launch',
  launchInstalledApp: (name: string) => `Launch ${name}`,
  noInstalledApps: 'No installed apps found',
  noAppSearchResults: (query: string) => `No apps match "${query}"`,
  deviceOptions: 'Device options',
  directCommands: 'Direct commands',
  directCommand: 'Direct command',
  tapX: 'Tap X',
  tapY: 'Tap Y',
  runTap: 'Run Tap',
  swipeFromX: 'From X',
  swipeFromY: 'From Y',
  swipeToX: 'To X',
  swipeToY: 'To Y',
  runSwipe: 'Run Swipe',
  directText: 'Text',
  runType: 'Run Type',
  runBack: 'Back',
  runHome: 'Home',
  runEnter: 'Enter',
  screenBlackoutDuringAutoControl: 'Dim screen during auto control',
  screenBlackoutDuringAutoControlHelp:
    'Sets the Android brightness to 0 while an automatic run is active, then restores it afterward.',
  useAdbKeyboard: 'Use ADB Keyboard for text',
  confirmSensitiveActions: 'Confirm sensitive actions',
  unrestrictedMode: 'Unrestricted mode',
  unrestrictedModeEnableTitle: 'Enable unrestricted mode?',
  unrestrictedModeEnablePrompt:
    'This mode lets the agent autonomously perform sensitive operations — including payments, account deletion, and factory resets — without any confirmation. Are you sure?',
  unrestrictedModeConfirm: 'I understand the risk, enable',
  unrestrictedModeCancel: 'Cancel',
  unrestrictedModeBlockedTitle: 'Irreversible action blocked by safety policy',
  unrestrictedModeBlockedPrompt:
    'Even in unrestricted mode, irreversible actions such as factory resets and account deletion still require manual confirmation.',
  unrestrictedModeEnabledBanner: 'Unrestricted mode enabled · sensitive actions run autonomously',
  sensitiveActionTitle: 'Sensitive action requested',
  sensitiveActionPrompt: 'Execute it?',
  actionSettle: 'Action settle (ms)',
  doubleTapInterval: 'Double tap interval (ms)',
  keyboardStep: 'Keyboard step (ms)',
  supportedActions: 'Supported actions',
  capabilities: [
    'Launch',
    'Tap',
    'Type',
    'Swipe',
    'Back',
    'Home',
    'Long press',
    'Double tap',
    'Wait',
    'Sequence',
    'Repeat',
    'Take over',
  ],
  actionNames: {
    back: 'Back',
    call_api: 'Call API',
    custom_tool: 'Custom tool',
    done: 'Done',
    double_tap: 'Double tap',
    home: 'Home',
    input_text: 'Input text',
    interact: 'Interact',
    key: 'Key press',
    launch: 'Launch',
    long_press: 'Long press',
    note: 'Note',
    open_url: 'Open URL',
    paste: 'Paste',
    repeat: 'Repeat',
    sequence: 'Sequence',
    set_clipboard: 'Set clipboard',
    swipe: 'Swipe',
    take_over: 'Take over',
    tap: 'Tap',
    type_secret: 'Type secret',
    view_screenshot: 'View screenshot',
    wait: 'Wait',
  },
  androidScreenshot: 'Android screenshot',
  expandedAndroidScreenshot: 'Expanded screenshot for Android screenshot',
  screenshotInteractionLayer: 'Screenshot interaction layer',
  runGeneratedAction: 'Run generated action',
  clearGeneratedAction: 'Clear generated action',
  openScreenshotFor: (title: string) => `Open screenshot for ${title}`,
  screenshotDialogFor: (title: string) => `Screenshot for ${title}`,
  closeScreenshotPreview: 'Close screenshot preview',
  screenshotZoomControls: 'Screenshot zoom controls',
  zoomInScreenshot: 'Zoom in screenshot',
  zoomOutScreenshot: 'Zoom out screenshot',
  resetScreenshotZoom: 'Reset screenshot zoom',
  showPhoneFullscreen: 'Show phone fullscreen',
  exitPhoneFullscreen: 'Exit phone fullscreen',
  fullscreenPhonePreview: 'Fullscreen phone preview',
  noScreenshot: 'No screenshot',
  noScreenshotHint: 'Connect and capture to show the live screen here',
  connectDeviceCta: 'Connect Android device',
  connectDeviceHint: 'USB debugging required — authorize on the phone when prompted',
  connectingDevice: 'Connecting…',
  capturingScreen: 'Capturing screen…',
  disconnectingDevice: 'Disconnecting…',
  chat: 'Chat',
  history: 'History',
  openHistorySidebar: 'Open history sidebar',
  closeHistorySidebar: 'Close history sidebar',
  recentChats: 'Recent chats',
  historyEmpty: 'No chat history yet.',
  historyNoMatches: 'No matching chats.',
  historyNoMatchesForQuery: (query: string) => `No chats match "${query}"`,
  historySearchAria: 'Search chat history',
  historySearchPlaceholder: 'Search history...',
  historySearchClear: 'Clear history search',
  openHistoryThread: (title: string) => `Open chat ${title}`,
  deleteHistoryThread: (title: string) => `Delete chat ${title}`,
  deleteThreadConfirm: (title: string) => `Delete chat "${title}"? This cannot be undone.`,
  conversation: 'Conversation',
  sessionState: 'Session state',
  sessionStatusIdle: 'Idle',
  sessionStatusRunning: 'Running',
  sessionStatusAwaitingReview: 'Needs review',
  sessionStatusAwaitingTakeover: 'Takeover',
  sessionStatusDone: 'Done',
  sessionStatusStopped: 'Stopped',
  sessionStatusError: 'Error',
  sessionStep: (step: number) => `Step #${step}`,
  queuedMessages: (count: number) => `${count} queued`,
  contextCompactedThroughStep: (step: number) => `Compacted through #${step}`,
  noMessages: 'No messages yet',
  chatEmptyNeedsDeviceTitle: 'Connect a phone first',
  chatEmptyNeedsDeviceBody: 'Once an Android device is connected, describe tasks in natural language.',
  chatEmptyNeedsModelTitle: 'Device is ready',
  chatEmptyNeedsModelBody: 'Configure Base URL, API Key, and Model to start running the agent.',
  chatEmptyReadyTitle: 'Describe a task for the phone',
  chatEmptyReadyBody: 'Or pick an example below to get started quickly.',
  chatEmptyConnectDevice: 'Connect device',
  chatEmptyConfigureModel: 'Configure model',
  useExamplePrompt: (prompt: string) => `Use example: ${prompt}`,
  quickStartPrompts: [
    'Open the Wi-Fi panel',
    'Capture and describe this screen',
    'Go back home',
  ],
  chatMessage: 'Chat message',
  chatPlaceholder: 'Send a follow-up instruction...',
  loopGuardStopped: 'Loop guard stopped the run',
  manualTakeoverRequested: 'Manual takeover requested',
  maxStepsReached: 'Max steps reached',
  send: 'Send',
  stopRun: 'Stop run',
  scrollToLatest: 'Scroll to latest',
  newChat: 'New chat',
  newChatStarted: 'New chat started',
  noAdbKeyboardDownloadSupport: 'This browser cannot download the ADB Keyboard APK.',
  typeMessageFirst: 'Type a message first.',
  runAgentTask: 'Run agent',
  screenBlackoutStartFailed: 'Could not dim the screen',
  screenBlackoutRestoreFailed: 'Could not restore screen brightness',
  runStopped: 'Run stopped',
  previousRunInterrupted: 'Previous run was interrupted before it finished.',
  waitForCurrentRun: 'Wait for the current run to finish.',
  maxSteps: 'Max steps',
  pendingAction: 'Pending action',
  screenCaptured: 'Screen captured',
  step: 'Step',
  stepPreview: (index: number, preview: string) => `Step ${index}: ${preview}`,
  stepAction: 'Action',
  stepResult: 'Result',
  stepDetails: 'Details',
  stepTool: 'Tool',
  stepExecutionResult: 'Execution result',
  stepModelOutput: 'Model output',
  stepParsedAction: 'Parsed action',
  stepTiming: (totalMs: number) => `Total ${totalMs} ms`,
  stepTimingSeconds: (seconds: number) => `${seconds} s`,
  stepTimingLessThanSecond: '<1 s',
  stepExecutionTiming: (executionMs: number) => `Tool ${executionMs} ms`,
  stepNoResult: 'Waiting for result',
  stepStatusPlanned: 'Planned',
  stepStatusRunning: 'Running',
  stepStatusExecuted: 'Executed',
  stepStatusFailed: 'Failed',
  stepStatusDone: 'Done',
  stepStatusAwaitingReview: 'Needs review',
  stepStatusTakeover: 'Takeover',
  none: 'None',
  acknowledge: 'Acknowledge',
  cancel: 'Cancel',
  finish: 'Finish',
  execute: 'Execute',
  user: 'User',
  assistant: 'Assistant',
  observation: 'Observation',
  taskComplete: 'Task complete',
  runLog: 'Run Log',
  clear: 'Clear',
  noEvents: 'No events yet',
  userMessage: 'User message',
  userMessageQueued: 'User message queued',
} as const
